const DATASETS={
  toses:{title:'Каталог ТОС',file:'/data/toses.json',download:'toses.json',label:x=>`ТОС «${x.name||'без названия'}»`,sub:x=>[x.location,x.chairperson].filter(Boolean).join(' · '),template:()=>({slug:'',name:'',type:'Городской',status:'published',location:'',boundaries:'',founded:'',chairperson:'',phones:[],emails:[],chairperson_links:[],social_links:[],population:'',description:'',logo:'',updated_at:today()}),fields:[['name','Название'],['slug','Slug'],['status','Статус','select:published|draft'],['type','Тип','select:Городской|Сельский'],['location','Территория'],['boundaries','Границы','textarea'],['founded','Год'],['chairperson','Председатель'],['population','Жителей'],['phones','Телефоны','array'],['emails','Email','array'],['chairperson_links','Ссылки председателя','array'],['social_links','Сообщества','array'],['description','Описание','textarea'],['logo','Логотип'],['updated_at','Дата обновления']]},
  news:{title:'Новости',file:'/data/news.json',download:'news.json',label:x=>x.title||'Новость без заголовка',sub:x=>[x.date,x.category,x.status].filter(Boolean).join(' · '),template:()=>({id:'news-'+Date.now(),status:'published',date:today(),category:'Новости ТОС',title:'',lead:'',text:[''],source:'Редакция портала',source_url:'',image:'',tos_slug:''}),fields:[['id','ID'],['status','Статус','select:published|draft'],['tos_slug','Привязка к ТОС','tosSlug'],['date','Дата'],['category','Категория'],['title','Заголовок'],['lead','Краткое описание','textarea'],['text','Текст абзацами','array'],['source','Источник'],['source_url','Ссылка'],['image','Изображение']]},
  articles:{title:'Материалы',file:'/data/articles.json',download:'articles.json',label:x=>x.title||'Материал без заголовка',sub:x=>[x.category,x.status].filter(Boolean).join(' · '),template:()=>({id:'material-'+Date.now(),status:'published',category:'Материал',title:'',lead:'',content:['']}),fields:[['id','ID'],['status','Статус','select:published|draft'],['category','Категория'],['title','Заголовок'],['lead','Описание','textarea'],['content','Текст','array']]},
  documents:{title:'Документы',file:'/data/documents.json',download:'documents.json',label:x=>x.title||'Документ без названия',sub:x=>[x.type,x.date].filter(Boolean).join(' · '),template:()=>({title:'',type:'Документ',status:'published',description:'',url:'',date:''}),fields:[['title','Название'],['status','Статус','select:published|draft'],['type','Тип'],['description','Описание','textarea'],['url','Ссылка'],['date','Дата/статус']]},
  grants:{title:'Конкурсы',file:'/data/grants.json',download:'grants.json',label:x=>x.title||'Конкурс без названия',sub:x=>[x.status,x.deadline].filter(Boolean).join(' · '),template:()=>({title:'',status:'Проверять актуальность',amount:'',budget:'',deadline:'',directions:'',who:'',source:'',note:''}),fields:[['title','Название'],['status','Статус'],['amount','Сумма'],['budget','Бюджет'],['deadline','Срок'],['directions','Направления','textarea'],['who','Кто участвует','textarea'],['source','Источник'],['note','Заметка','textarea']]},
  projects:{title:'Проекты',file:'/data/projects.json',download:'projects.json',label:x=>x.title||'Проект без названия',sub:x=>[x.type,x.status,x.tos_slug].filter(Boolean).join(' · '),template:()=>({id:'project-'+Date.now(),status:'published',tos_slug:'',title:'',type:'Идея проекта',description:'',steps:['']}),fields:[['id','ID'],['status','Статус','select:published|draft'],['tos_slug','Привязка к ТОС','tosSlug'],['title','Название'],['type','Тип'],['description','Описание','textarea'],['steps','Шаги','array']]},
  events:{title:'Календарь',file:'/data/events.json',download:'events.json',label:x=>x.title||'Событие без названия',sub:x=>[x.date,x.type,x.tos_slug].filter(Boolean).join(' · '),template:()=>({id:'event-'+Date.now(),status:'published',date:today(),time:'',type:'Событие',title:'',description:'',place:'',tos_slug:'',source:'Редакция портала',source_url:''}),fields:[['id','ID'],['status','Статус','select:published|draft'],['date','Дата'],['time','Время'],['type','Тип события'],['tos_slug','Привязка к ТОС','tosSlug'],['title','Название'],['description','Описание','textarea'],['place','Место'],['source','Источник'],['source_url','Ссылка']]},
  needs:{title:'Нужна помощь',file:'/data/needs.json',download:'needs.json',label:x=>x.title||'Потребность без названия',sub:x=>[x.need_type,x.priority,x.tos_slug].filter(Boolean).join(' · '),template:()=>({id:'need-'+Date.now(),status:'published',date:today(),tos_slug:'',title:'',description:'',need_type:'Помощь',priority:'Средний',contact:'',source:'Редакция портала',source_url:''}),fields:[['id','ID'],['status','Статус','select:published|draft'],['date','Дата'],['tos_slug','Привязка к ТОС','tosSlug'],['title','Название'],['description','Описание','textarea'],['need_type','Тип помощи'],['priority','Приоритет','select:Высокий|Средний|Низкий'],['contact','Контакт'],['source','Источник'],['source_url','Ссылка']]}
};
const state={section:'toses',data:{},selected:0,query:'',filter:'',tosOptions:[]};
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function today(){return new Date().toISOString().slice(0,10)}
function sk(k){return 'tosbgo_admin_'+k}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function slugify(t){const m={а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'y',к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',х:'h',ц:'c',ч:'ch',ш:'sh',щ:'sch',ъ:'',ы:'y',ь:'',э:'e',ю:'yu',я:'ya'};return String(t||'').toLowerCase().split('').map(ch=>m[ch]??ch).join('').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'item'}
function current(){return state.data[state.section]||[]}
function save(){localStorage.setItem(sk(state.section),JSON.stringify(current()))}
async function ensureTosOptions(){if(state.tosOptions.length)return;try{const d=localStorage.getItem(sk('toses'));const arr=d?JSON.parse(d):await(await fetch('/data/toses.json',{cache:'no-store'})).json();state.tosOptions=arr.filter(x=>x.slug).map(x=>({slug:x.slug,name:x.name||x.slug,location:x.location||''})).sort((a,b)=>a.name.localeCompare(b.name,'ru'))}catch{state.tosOptions=[]}}
async function loadSection(sec){state.section=sec;state.selected=0;state.query='';state.filter='';$('#helpSection').classList.toggle('hidden',sec!=='help');$('#editorSection').classList.toggle('hidden',sec==='help');$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.section===sec));if(sec==='help')return;await ensureTosOptions();const cfg=DATASETS[sec];$('#sectionTitle').textContent=cfg.title;$('#sectionHint').textContent='Редактирование '+cfg.file;$('#searchInput').value='';buildFilters();const draft=localStorage.getItem(sk(sec));if(draft){try{state.data[sec]=JSON.parse(draft)}catch{localStorage.removeItem(sk(sec))}}if(!state.data[sec]){try{state.data[sec]=await(await fetch(cfg.file,{cache:'no-store'})).json()}catch{state.data[sec]=[]}}renderList();renderForm()}
function buildFilters(){let opts=[['','Все записи'],['published','Опубликованные'],['draft','Черновики'],['low','Заполнено менее 70%']];if(['news','projects','events','needs'].includes(state.section))opts.push(['linked','Привязаны к ТОС']);$('#quickFilter').innerHTML=opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}
function quality(x){let req=['title']; if(state.section==='toses')req=['name','slug','location','boundaries','chairperson','description']; if(state.section==='news')req=['id','date','title','lead','text']; if(state.section==='events')req=['id','date','type','title','description']; if(state.section==='needs')req=['id','date','title','description','need_type','priority','contact']; let ok=req.filter(k=>Array.isArray(x[k])?x[k].length:!!x[k]).length; return Math.round(ok/req.length*100)}
function pass(x){if(state.filter==='draft')return x.status==='draft';if(state.filter==='published')return x.status!=='draft';if(state.filter==='linked')return !!x.tos_slug;if(state.filter==='low')return quality(x)<70;return true}
function filtered(){const q=state.query.toLowerCase().trim();return current().map((item,index)=>({item,index})).filter(({item})=>(!q||JSON.stringify(item).toLowerCase().includes(q))&&pass(item))}
function renderList(){const cfg=DATASETS[state.section],list=$('#itemsList'),items=filtered();if(!items.length){list.innerHTML='<div class="empty">Записей не найдено.</div>';return}list.innerHTML=items.map(({item,index})=>`<button class="item ${index===state.selected?'active':''}" data-index="${index}" type="button"><b>${esc(cfg.label(item))}</b><span>${esc(cfg.sub(item))}</span><em class="score">Заполнено: ${quality(item)}%</em></button>`).join('');$$('.item',list).forEach(b=>b.onclick=()=>{state.selected=+b.dataset.index;renderList();renderForm()})}
function renderField(item,[key,label,type='text']){const val=item[key];const full=['textarea','array','tosSlug'].includes(type)?' full':'';if(type==='tosSlug'){const opts=state.tosOptions.map(x=>`<option value="${esc(x.slug)}">ТОС «${esc(x.name)}» — ${esc(x.slug)}</option>`).join('');return `<div class="field full"><label>${label}</label><input list="tos-slug-list" data-key="${key}" value="${esc(val)}" placeholder="Например: uyutnyy"><datalist id="tos-slug-list">${opts}</datalist><small>Выберите ТОС из списка или введите slug вручную.</small></div>`}if(key==='logo'){return `<div class="field${full}"><label>${label}</label><input data-key="${key}" value="${esc(val)}" placeholder="/assets/img/tos-logos/${esc(item.slug||'slug')}.svg"><small>Рекомендуемый путь: /assets/img/tos-logos/${esc(item.slug||'slug')}.svg. Файл нужно загрузить в папку assets/img/tos-logos/.</small></div>`}if(type.startsWith('select:')){return `<div class="field${full}"><label>${label}</label><select data-key="${key}">${type.replace('select:','').split('|').map(o=>`<option ${val===o?'selected':''}>${o}</option>`).join('')}</select></div>`}if(type==='textarea')return `<div class="field full"><label>${label}</label><textarea data-key="${key}">${esc(val)}</textarea></div>`;if(type==='array'){const arr=Array.isArray(val)?val:(val?[val]:[]);return `<div class="field full array-field" data-array-key="${key}"><label>${label}</label><div class="array-list">${arr.map((v,i)=>`<div class="array-row"><textarea data-array-index="${i}">${esc(v)}</textarea><button class="btn danger" type="button" data-remove-array="${i}">×</button></div>`).join('')}</div><button class="btn" type="button" data-add-array="${key}">Добавить строку</button></div>`}return `<div class="field${full}"><label>${label}</label><input data-key="${key}" value="${esc(val)}"></div>`}
function renderForm(){const item=current()[state.selected],form=$('#editForm'),cfg=DATASETS[state.section];if(!item){form.innerHTML='<div class="empty">Выберите запись или добавьте новую.</div>';return}form.innerHTML=`<div class="form-grid">${cfg.fields.map(f=>renderField(item,f)).join('')}</div><div class="form-actions"><button class="btn primary" type="button" id="saveItem">Сохранить в черновик</button><button class="btn" type="button" id="duplicateItem">Дублировать</button><button class="btn danger" type="button" id="deleteItem">Удалить</button><button class="btn" type="button" id="autoFill">Автозаполнение</button><button class="btn" type="button" id="fillLogo">Путь к логотипу</button><button class="btn" type="button" id="copyItemJson">Копировать JSON записи</button></div><div class="preview" id="previewBox"></div>`;bind(item);preview(item)}
function bind(item){$$('[data-key]').forEach(el=>el.oninput=()=>{item[el.dataset.key]=el.value;save();renderList();preview(item)});$$('[data-array-key]').forEach(box=>{const k=box.dataset.arrayKey;if(!Array.isArray(item[k]))item[k]=[];$$('[data-array-index]',box).forEach(el=>el.oninput=()=>{item[k][+el.dataset.arrayIndex]=el.value;save();preview(item)});$$('[data-remove-array]',box).forEach(b=>b.onclick=()=>{item[k].splice(+b.dataset.removeArray,1);save();renderForm()});$('[data-add-array]',box).onclick=()=>{item[k].push('');save();renderForm()}});$('#saveItem').onclick=()=>{save();msg(['Черновик сохранён.'],true)};$('#deleteItem').onclick=()=>{if(confirm('Удалить запись?')){current().splice(state.selected,1);state.selected=0;save();renderList();renderForm()}};$('#duplicateItem').onclick=()=>{const c=JSON.parse(JSON.stringify(item));if(c.id)c.id+='-copy';if(c.slug)c.slug+='-copy';current().splice(state.selected+1,0,c);state.selected++;save();renderList();renderForm()};$('#autoFill').onclick=()=>{if(item.name&&!item.slug)item.slug=slugify(item.name);if(item.title&&!item.id)item.id=slugify(item.title);if(!item.status)item.status='published';if(!item.updated_at&&state.section==='toses')item.updated_at=today();if(state.section==='toses'&&item.slug&&!item.logo)item.logo='/assets/img/tos-logos/'+item.slug+'.svg';save();renderForm()};$('#fillLogo').onclick=()=>{if(state.section==='toses'){if(!item.slug&&item.name)item.slug=slugify(item.name);if(item.slug)item.logo='/assets/img/tos-logos/'+item.slug+'.svg';save();renderForm();msg(['Путь к логотипу сформирован. Теперь загрузите файл с таким именем в assets/img/tos-logos/.'],true)}else{msg(['Кнопка используется только в разделе «Каталог ТОС».'],false)}};$('#copyItemJson').onclick=async()=>{await navigator.clipboard?.writeText(JSON.stringify(item,null,2));msg(['JSON записи скопирован.'],true)}}
function preview(x){const tos=state.tosOptions.find(t=>t.slug===x.tos_slug);$('#previewBox').innerHTML=`<h3>${esc(x.title||x.name||'Запись без названия')}</h3><p>${esc(x.lead||x.description||x.boundaries||x.note||'').slice(0,500)}</p><p class="quality-score">Заполнено: ${quality(x)}%</p>${x.logo?`<p><b>Логотип:</b> ${esc(x.logo)}</p>`:''}${x.tos_slug?`<p><b>Привязка к ТОС:</b> ${esc(tos?'ТОС «'+tos.name+'» ('+tos.slug+')':x.tos_slug)}</p>`:''}`}
function validate(){let errors=[],seen=new Set();current().forEach((x,i)=>{const name=x.name||x.title||x.id||`запись ${i+1}`;const key=x.slug||x.id;if(key){if(seen.has(key))errors.push('Дубль: '+name);seen.add(key)}if(x.tos_slug&&state.tosOptions.length&&!state.tosOptions.some(t=>t.slug===x.tos_slug))errors.push(`${name}: tos_slug «${x.tos_slug}» не найден.`);if(state.section==='toses'&&x.logo&&!x.logo.startsWith('/assets/img/tos-logos/'))errors.push(`${name}: логотип лучше хранить в /assets/img/tos-logos/.`) });msg(errors.length?errors:['Ошибок не найдено.'],!errors.length)}
function audit(){const rows=current().map(x=>({x,q:quality(x)})).sort((a,b)=>a.q-b.q);$('#validationBox').classList.remove('hidden');$('#validationBox').classList.remove('ok');$('#validationBox').innerHTML='<b>Аудит качества</b><div class="quality-list">'+rows.slice(0,20).map(r=>`<div class="quality-row"><div class="quality-score">${r.q}%</div><div><b>${esc(r.x.name||r.x.title||r.x.id||'Запись')}</b></div></div>`).join('')+'</div>'}
function msg(arr,ok){const b=$('#validationBox');b.classList.remove('hidden');b.classList.toggle('ok',!!ok);b.innerHTML=`<b>${ok?'Готово':'Найдены замечания'}</b><ul>${arr.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
function downloadText(name,text,type='application/json;charset=utf-8'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function downloadJson(){downloadText(DATASETS[state.section].download,JSON.stringify(current(),null,2))}
async function downloadAll(){for(const k of Object.keys(DATASETS)){if(!state.data[k]){try{state.data[k]=JSON.parse(localStorage.getItem(sk(k)))||await(await fetch(DATASETS[k].file,{cache:'no-store'})).json()}catch{state.data[k]=[]}}}downloadText('tos-bgo-json-backup-'+today()+'.json',JSON.stringify(Object.fromEntries(Object.keys(DATASETS).map(k=>[DATASETS[k].download,state.data[k]])),null,2))}
function importJson(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p))throw new Error('Нужен массив JSON');state.data[state.section]=p;state.selected=0;if(state.section==='toses')state.tosOptions=[];save();renderList();renderForm();msg(['Файл загружен.'],true)}catch(e){msg(['Ошибка импорта: '+e.message],false)}};r.readAsText(file)}
function add(){current().unshift(DATASETS[state.section].template());state.selected=0;save();renderList();renderForm()}
$$('.tab').forEach(b=>b.onclick=()=>loadSection(b.dataset.section));$('#searchInput').oninput=e=>{state.query=e.target.value;renderList()};$('#quickFilter').onchange=e=>{state.filter=e.target.value;renderList()};$('#addItem').onclick=add;$('#downloadJson').onclick=downloadJson;$('#downloadAllJson').onclick=downloadAll;$('#importJson').onclick=()=>$('#importJsonFile').click();$('#importJsonFile').onchange=e=>importJson(e.target.files[0]);$('#validateBtn').onclick=validate;$('#qualityBtn').onclick=audit;$('#resetLocal').onclick=()=>{if(confirm('Удалить локальные черновики?')){Object.keys(DATASETS).forEach(k=>localStorage.removeItem(sk(k)));location.reload()}};
loadSection('toses');
