const projectModeChecks = [
  ['CSV parser', 'scripts/test_csv_parser.js'],
  ['CSV schema', 'scripts/test_csv_schema.js'],
  ['Date checks', 'scripts/test_date_checks.js'],
  ['ID checks', 'scripts/test_id_checks.js'],
  ['Path checks', 'scripts/test_path_checks.js'],
  ['Status sets', 'scripts/test_status_sets.js'],
  ['TOS integrity', 'scripts/audit_tos_integrity.js'],
  ['TOS catalog content', 'scripts/audit_tos_catalog_content.js'],
  ['TOS detail pages content', 'scripts/audit_tos_detail_pages_content.js'],
  ['Projects integrity', 'scripts/audit_projects_integrity.js'],
  ['Project pages content', 'scripts/audit_project_pages_content.js'],
  ['Projects action routes content', 'scripts/audit_projects_action_routes_content.js'],
  ['Grants page content', 'scripts/audit_grants_page_content.js'],
  ['Materials page content', 'scripts/audit_materials_page_content.js'],
  ['Documents page content', 'scripts/audit_documents_page_content.js'],
  ['Legal page content', 'scripts/audit_legal_page_content.js'],
  ['Contacts page content', 'scripts/audit_contacts_page_content.js'],
  ['Communication kit content', 'scripts/audit_communication_kit_content.js'],
  ['Field checklist content', 'scripts/audit_field_checklist_content.js'],
  ['Reply review content', 'scripts/audit_reply_review_content.js'],
  ['Privacy content', 'scripts/audit_privacy_content.js'],
  ['Sources content', 'scripts/audit_sources_content.js'],
  ['Source watch content', 'scripts/audit_source_watch_content.js'],
  ['Content discovery content', 'scripts/audit_content_discovery_content.js'],
  ['Project check 2026 content', 'scripts/audit_project_check_2026_content.js'],
  ['Projects 2026 result requests content', 'scripts/audit_projects_2026_result_requests_content.js'],
  ['Chairperson page content', 'scripts/audit_chairperson_page_content.js'],
  ['Chairperson first 30 days content', 'scripts/audit_chairperson_first_30_days_content.js'],
  ['Chairperson verify card content', 'scripts/audit_chairperson_verify_card_content.js'],
  ['Chairperson meeting content', 'scripts/audit_chairperson_meeting_content.js'],
  ['Chairperson project content', 'scripts/audit_chairperson_project_content.js'],
  ['Chairperson documents content', 'scripts/audit_chairperson_documents_content.js'],
  ['Chairperson news content', 'scripts/audit_chairperson_news_content.js'],
  ['Chairperson conflicts content', 'scripts/audit_chairperson_conflicts_content.js'],
  ['Chairperson action routes content', 'scripts/audit_chairperson_action_routes_content.js'],
  ['Residents page content', 'scripts/audit_residents_page_content.js'],
  ['Residents action routes content', 'scripts/audit_residents_action_routes_content.js'],
  ['Partners page content', 'scripts/audit_partners_page_content.js'],
  ['Partners action routes content', 'scripts/audit_partners_action_routes_content.js'],
  ['Calendar page content', 'scripts/audit_calendar_page_content.js'],
  ['Calendar action routes content', 'scripts/audit_calendar_action_routes_content.js'],
  ['Projects 2026 workflow', 'scripts/audit_projects_2026_workflow.js'],
  ['Needs integrity', 'scripts/audit_needs_integrity.js'],
  ['Needs pages content', 'scripts/audit_needs_pages_content.js'],
  ['Needs action routes content', 'scripts/audit_needs_action_routes_content.js'],
  ['Done integrity', 'scripts/audit_done_integrity.js'],
  ['Done pages content', 'scripts/audit_done_pages_content.js'],
  ['Done action routes content', 'scripts/audit_done_action_routes_content.js'],
  ['Content intake template', 'scripts/audit_content_intake_template.js'],
  ['Publication consent checklist', 'scripts/audit_publication_consent_checklist.js'],
  ['Publication queue', 'scripts/audit_publication_queue.js'],
  ['Publication queue content', 'scripts/audit_publication_queue_content.js'],
  ['Media intake register', 'scripts/audit_media_intake_register.js'],
  ['Source watchlist', 'scripts/audit_source_watchlist.js'],
  ['Content discovery log', 'scripts/audit_content_discovery_log.js'],
  ['Editorial calendar', 'scripts/audit_editorial_calendar.js'],
  ['Content freshness check', 'scripts/audit_content_freshness_check.js'],
  ['Post-publish QA checklist', 'scripts/audit_post_publish_qa_checklist.js'],
  ['Quarterly report template', 'scripts/audit_quarterly_report_template.js'],
  ['Collection tasks', 'scripts/audit_collection_tasks.js'],
  ['Priority TOS tracking', 'scripts/audit_priority_tos_tracking.js'],
  ['Registry workflow', 'scripts/audit_registry_workflow.js'],
  ['CSS maintenance inventory', 'scripts/audit_css_maintenance_inventory.js'],
  ['Technical diagnostics', 'scripts/audit_technical_diagnostics.js'],
  ['Open data links', 'scripts/audit_open_data_links.js'],
  ['Autonomous improvement plan', 'scripts/audit_autonomous_improvement_plan.js'],
  ['User decision queue', 'scripts/audit_user_decision_queue.js'],
  ['Manual tasks', 'scripts/audit_github_manual_tasks.js'],
  ['Request source tables', 'scripts/audit_request_sources.js'],
  ['Request source imports', 'scripts/test_request_sources_import.js'],
  ['Request source status values', 'scripts/test_request_source_status_values.js'],
  ['Verification tasks', 'scripts/audit_verification_tasks.js'],
  ['Verification pilot', 'scripts/audit_verification_pilot.js'],
  ['Verification source tables', 'scripts/audit_verification_sources.js'],
  ['Outreach register', 'scripts/audit_outreach_register.js'],
  ['Outreach register content', 'scripts/audit_outreach_register_content.js'],
  ['Outreach source index', 'scripts/test_outreach_source_index.js'],
  ['Site health', 'scripts/audit_site_health.js'],
  ['Homepage content', 'scripts/audit_homepage_content.js'],
  ['Update center content', 'scripts/audit_update_center_content.js'],
  ['Search content', 'scripts/audit_search_content.js'],
  ['News page content', 'scripts/audit_news_page_content.js'],
  ['News detail pages content', 'scripts/audit_news_detail_pages_content.js'],
  ['Page index', 'scripts/audit_page_index.js'],
  ['Sitemap', 'scripts/audit_sitemap.js'],
  ['News data', 'scripts/audit_news_data.js'],
  ['RSS', 'scripts/audit_rss.js'],
  ['Run checks helper', 'scripts/test_run_checks.js']
];

const projectModeFullChecks = projectModeChecks.map(([label, scriptPath]) => {
  if (label.includes('parser') || label.includes('schema') || label.includes('checks') || label.includes('imports') || label.includes('values') || label.includes('index') || label.includes('helper')) {
    return [`${label} self-test`, scriptPath];
  }

  return [`${label} audit`, scriptPath];
});

module.exports = {
  projectModeChecks,
  projectModeFullChecks
};
