const { runChecks } = require('./lib/run_checks');

runChecks([
  ['visual comparison policy self-test', 'scripts/test_visual_comparison_policy.js'],
  ['collection browser core self-test', 'scripts/test_collection_browser_core.js'],
  ['collection browser pages', 'scripts/audit_collection_browsers.js'],
  ['data quality page', 'scripts/audit_data_quality_content.js'],
  ['media guide page', 'scripts/audit_media_guide_content.js'],
  ['places page', 'scripts/audit_places_content.js'],
  ['map page', 'scripts/audit_map_content.js'],
  ['rss feed content', 'scripts/audit_rss_feed_content.js'],
  ['required project ids', 'scripts/audit_projects_required_ids.js'],
  ['required done ids', 'scripts/audit_done_required_ids.js'],
  ['collection context navigation', 'scripts/audit_collection_context_navigation.js'],
  ['material detail pages', 'scripts/audit_material_detail_pages_content.js'],
  ['required catalog slugs', 'scripts/audit_required_slugs.js'],
  ['submit materials page', 'scripts/audit_submit_materials_content.js'],
  ['verification levels page', 'scripts/audit_verification_levels_content.js'],
  ['actions check page', 'scripts/audit_actions_check_content.js'],
  ['GitHub Pages manual check wizard self-test', 'scripts/test_github_pages_manual_check.js'],
  ['GitHub Pages manual check wizard', 'scripts/audit_github_pages_manual_check.js'],
  ['outreach execution packet self-test', 'scripts/test_outreach_execution.js'],
  ['outreach execution packet', 'scripts/audit_outreach_execution.js'],
  ['publication basis execution self-test', 'scripts/test_publication_basis_execution.js'],
  ['publication basis confirmation register', 'scripts/audit_publication_basis_confirmation_register.js'],
  ['publication basis review page', 'scripts/audit_publication_basis_review_page.js'],
  ['personal data decision packet self-test', 'scripts/test_personal_data_decision_packet.js'],
  ['personal data decision packet', 'scripts/audit_personal_data_decision_packet.js'],
  ['personal data decision page', 'scripts/audit_personal_data_decision_page.js'],
  ['personal data scenario matrix self-test', 'scripts/test_personal_data_scenario_matrix.js'],
  ['personal data scenario matrix', 'scripts/audit_personal_data_scenario_matrix.js'],
  ['personal data scenario page', 'scripts/audit_personal_data_scenario_page.js'],
  ['media permission scenarios self-test', 'scripts/test_media_permission_scenarios.js'],
  ['media permission scenarios', 'scripts/audit_media_permission_scenarios.js'],
  ['media permission scenario page', 'scripts/audit_media_permission_scenario_page.js'],
  ['withdrawal correction deletion process self-test', 'scripts/test_withdrawal_correction_deletion_process.js'],
  ['withdrawal correction deletion process', 'scripts/audit_withdrawal_correction_deletion_process.js'],
  ['withdrawal correction deletion page', 'scripts/audit_withdrawal_correction_deletion_page.js'],
  ['private evidence storage requirements self-test', 'scripts/test_private_evidence_storage_requirements.js'],
  ['private evidence storage requirements', 'scripts/audit_private_evidence_storage_requirements.js'],
  ['private evidence storage page', 'scripts/audit_private_evidence_storage_page.js'],
  ['retention access incident rules self-test', 'scripts/test_retention_access_incident_rules.js'],
  ['retention access incident rules', 'scripts/audit_retention_access_incident_rules.js'],
  ['retention access incident page', 'scripts/audit_retention_access_incident_page.js'],
  ['workbench manual blockers', 'scripts/audit_workbench_manual_blockers.js']
], {
  verbose: true,
  successMessage: 'Manual audit extensions OK'
});
