const { runChecks } = require('./lib/run_checks');

const checks = [
  ['CSV parser self-test', 'scripts/test_csv_parser.js'],
  ['CSV schema self-test', 'scripts/test_csv_schema.js'],
  ['Date checks self-test', 'scripts/test_date_checks.js'],
  ['ID checks self-test', 'scripts/test_id_checks.js'],
  ['Path checks self-test', 'scripts/test_path_checks.js'],
  ['Status sets self-test', 'scripts/test_status_sets.js'],
  ['Content origins audit', 'scripts/audit_content_origins.js'],
  ['Supabase scope audit', 'scripts/audit_supabase_scope.js'],
  ['Foreign module quarantine audit', 'scripts/audit_foreign_module_inventory.js'],
  ['TOS integrity audit', 'scripts/audit_tos_integrity.js'],
  ['TOS catalog content audit', 'scripts/audit_tos_catalog_content.js'],
  ['TOS detail pages content audit', 'scripts/audit_tos_detail_pages_content.js'],
  ['Projects integrity audit', 'scripts/audit_projects_integrity.js'],
  ['Project pages content audit', 'scripts/audit_project_pages_content.js'],
  ['Projects action routes content audit', 'scripts/audit_projects_action_routes_content.js'],
  ['Grants page content audit', 'scripts/audit_grants_page_content.js'],
  ['Materials page content audit', 'scripts/audit_materials_page_content.js'],
  ['Documents page content audit', 'scripts/audit_documents_page_content.js'],
  ['Legal page content audit', 'scripts/audit_legal_page_content.js'],
  ['Contacts page content audit', 'scripts/audit_contacts_page_content.js'],
  ['Communication kit content audit', 'scripts/audit_communication_kit_content.js'],
  ['Field checklist content audit', 'scripts/audit_field_checklist_content.js'],
  ['Reply review content audit', 'scripts/audit_reply_review_content.js'],
  ['Privacy content audit', 'scripts/audit_privacy_content.js'],
  ['Sources content audit', 'scripts/audit_sources_content.js'],
  ['Source watch content audit', 'scripts/audit_source_watch_content.js'],
  ['Content discovery content audit', 'scripts/audit_content_discovery_content.js'],
  ['Project check 2026 content audit', 'scripts/audit_project_check_2026_content.js'],
  ['Projects 2026 result requests content audit', 'scripts/audit_projects_2026_result_requests_content.js'],
  ['Chairperson page content audit', 'scripts/audit_chairperson_page_content.js'],
  ['Chairperson first 30 days content audit', 'scripts/audit_chairperson_first_30_days_content.js'],
  ['Chairperson verify card content audit', 'scripts/audit_chairperson_verify_card_content.js'],
  ['Chairperson meeting content audit', 'scripts/audit_chairperson_meeting_content.js'],
  ['Chairperson project content audit', 'scripts/audit_chairperson_project_content.js'],
  ['Chairperson documents content audit', 'scripts/audit_chairperson_documents_content.js'],
  ['Chairperson news content audit', 'scripts/audit_chairperson_news_content.js'],
  ['Chairperson conflicts content audit', 'scripts/audit_chairperson_conflicts_content.js'],
  ['Chairperson action routes content audit', 'scripts/audit_chairperson_action_routes_content.js'],
  ['Residents page content audit', 'scripts/audit_residents_page_content.js'],
  ['Residents action routes content audit', 'scripts/audit_residents_action_routes_content.js'],
  ['Partners page content audit', 'scripts/audit_partners_page_content.js'],
  ['Partners action routes content audit', 'scripts/audit_partners_action_routes_content.js'],
  ['Calendar page content audit', 'scripts/audit_calendar_page_content.js'],
  ['Calendar action routes content audit', 'scripts/audit_calendar_action_routes_content.js'],
  ['Projects 2026 workflow audit', 'scripts/audit_projects_2026_workflow.js'],
  ['Needs integrity audit', 'scripts/audit_needs_integrity.js'],
  ['Needs pages content audit', 'scripts/audit_needs_pages_content.js'],
  ['Needs action routes content audit', 'scripts/audit_needs_action_routes_content.js'],
  ['Done integrity audit', 'scripts/audit_done_integrity.js'],
  ['Done pages content audit', 'scripts/audit_done_pages_content.js'],
  ['Done action routes content audit', 'scripts/audit_done_action_routes_content.js'],
  ['Content intake template audit', 'scripts/audit_content_intake_template.js'],
  ['Publication consent checklist audit', 'scripts/audit_publication_consent_checklist.js'],
  ['Publication queue audit', 'scripts/audit_publication_queue.js'],
  ['Media intake register audit', 'scripts/audit_media_intake_register.js'],
  ['Source watchlist audit', 'scripts/audit_source_watchlist.js'],
  ['Content discovery log audit', 'scripts/audit_content_discovery_log.js'],
  ['Editorial calendar audit', 'scripts/audit_editorial_calendar.js'],
  ['Content freshness check audit', 'scripts/audit_content_freshness_check.js'],
  ['Post-publish QA checklist audit', 'scripts/audit_post_publish_qa_checklist.js'],
  ['Quarterly report template audit', 'scripts/audit_quarterly_report_template.js'],
  ['Collection tasks audit', 'scripts/audit_collection_tasks.js'],
  ['Priority TOS tracking audit', 'scripts/audit_priority_tos_tracking.js'],
  ['Priority TOS response review audit', 'scripts/audit_priority_tos_response_review.js'],
  ['Priority TOS update evidence audit', 'scripts/audit_priority_tos_update_evidence.js'],
  ['Priority TOS update evidence self-test', 'scripts/test_priority_tos_update_evidence.js'],
  ['Priority TOS readiness audit', 'scripts/audit_priority_tos_readiness.js'],
  ['Registry workflow audit', 'scripts/audit_registry_workflow.js'],
  ['CSS maintenance inventory audit', 'scripts/audit_css_maintenance_inventory.js'],
  ['CSS visual regression matrix audit', 'scripts/audit_css_regression_matrix.js'],
  ['Technical diagnostics audit', 'scripts/audit_technical_diagnostics.js'],
  ['Open data links audit', 'scripts/audit_open_data_links.js'],
  ['Autonomous improvement plan audit', 'scripts/audit_autonomous_improvement_plan.js'],
  ['User decision queue audit', 'scripts/audit_user_decision_queue.js'],
  ['Manual tasks audit', 'scripts/audit_github_manual_tasks.js'],
  ['Request source tables audit', 'scripts/audit_request_sources.js'],
  ['Request source imports self-test', 'scripts/test_request_sources_import.js'],
  ['Request source status values self-test', 'scripts/test_request_source_status_values.js'],
  ['Verification tasks audit', 'scripts/audit_verification_tasks.js'],
  ['Verification pilot audit', 'scripts/audit_verification_pilot.js'],
  ['Verification source tables audit', 'scripts/audit_verification_sources.js'],
  ['Outreach register audit', 'scripts/audit_outreach_register.js'],
  ['Outreach register content audit', 'scripts/audit_outreach_register_content.js'],
  ['Outreach source index self-test', 'scripts/test_outreach_source_index.js'],
  ['Site health audit', 'scripts/audit_site_health.js'],
  ['Homepage content audit', 'scripts/audit_homepage_content.js'],
  ['Update center content audit', 'scripts/audit_update_center_content.js'],
  ['Search content audit', 'scripts/audit_search_content.js'],
  ['News page content audit', 'scripts/audit_news_page_content.js'],
  ['News detail pages content audit', 'scripts/audit_news_detail_pages_content.js'],
  ['Page index audit', 'scripts/audit_page_index.js'],
  ['Sitemap audit', 'scripts/audit_sitemap.js'],
  ['News data audit', 'scripts/audit_news_data.js'],
  ['RSS feed audit', 'scripts/audit_rss.js'],
  ['Run checks helper self-test', 'scripts/test_run_checks.js']
];

runChecks(checks, {
  verbose: true,
  successMessage: 'Project mode full audit OK'
});
