const { runChecks } = require('./lib/run_checks');

const checks = [
  ['CSV parser', 'scripts/test_csv_parser.js'],
  ['CSV schema', 'scripts/test_csv_schema.js'],
  ['Date checks', 'scripts/test_date_checks.js'],
  ['ID checks', 'scripts/test_id_checks.js'],
  ['Path checks', 'scripts/test_path_checks.js'],
  ['Status sets', 'scripts/test_status_sets.js'],
  ['TOS integrity', 'scripts/audit_tos_integrity.js'],
  ['TOS catalog content', 'scripts/audit_tos_catalog_content.js'],
  ['TOS detail pages content', 'scripts/audit_tos_detail_pages_content.js'],
  ['Projects integrity', 'scripts/audit_projects_integrity.js'],
  ['Project pages content', 'scripts/audit_project_pages_content.js'],
  ['Grants page content', 'scripts/audit_grants_page_content.js'],
  ['Materials page content', 'scripts/audit_materials_page_content.js'],
  ['Documents page content', 'scripts/audit_documents_page_content.js'],
  ['Legal page content', 'scripts/audit_legal_page_content.js'],
  ['Contacts page content', 'scripts/audit_contacts_page_content.js'],
  ['Residents page content', 'scripts/audit_residents_page_content.js'],
  ['Residents action routes content', 'scripts/audit_residents_action_routes_content.js'],
  ['Partners page content', 'scripts/audit_partners_page_content.js'],
  ['Partners action routes content', 'scripts/audit_partners_action_routes_content.js'],
  ['Projects 2026 workflow', 'scripts/audit_projects_2026_workflow.js'],
  ['Needs integrity', 'scripts/audit_needs_integrity.js'],
  ['Needs pages content', 'scripts/audit_needs_pages_content.js'],
  ['Done integrity', 'scripts/audit_done_integrity.js'],
  ['Done pages content', 'scripts/audit_done_pages_content.js'],
  ['Content intake template', 'scripts/audit_content_intake_template.js'],
  ['Publication consent checklist', 'scripts/audit_publication_consent_checklist.js'],
  ['Publication queue', 'scripts/audit_publication_queue.js'],
  ['Media intake register', 'scripts/audit_media_intake_register.js'],
  ['Source watchlist', 'scripts/audit_source_watchlist.js'],
  ['Content discovery log', 'scripts/audit_content_discovery_log.js'],
  ['Editorial calendar', 'scripts/audit_editorial_calendar.js'],
  ['Content freshness check', 'scripts/audit_content_freshness_check.js'],
  ['Post-publish QA checklist', 'scripts/audit_post_publish_qa_checklist.js'],
  ['Quarterly report template', 'scripts/audit_quarterly_report_template.js'],
  ['Collection tasks', 'scripts/audit_collection_tasks.js'],
  ['Priority TOS tracking', 'scripts/audit_priority_tos_tracking.js'],
  ['Registry workflow', 'scripts/audit_registry_workflow.js'],
  ['CSS maintenance inventory', 'scripts/audit_css_maintenance_inventory.js'],
  ['Technical diagnostics', 'scripts/audit_technical_diagnostics.js'],
  ['Open data links', 'scripts/audit_open_data_links.js'],
  ['Autonomous improvement plan', 'scripts/audit_autonomous_improvement_plan.js'],
  ['User decision queue', 'scripts/audit_user_decision_queue.js'],
  ['Manual tasks', 'scripts/audit_github_manual_tasks.js'],
  ['Request source tables', 'scripts/audit_request_sources.js'],
  ['Request source imports', 'scripts/test_request_sources_import.js'],
  ['Request source status values', 'scripts/test_request_source_status_values.js'],
  ['Verification tasks', 'scripts/audit_verification_tasks.js'],
  ['Verification pilot', 'scripts/audit_verification_pilot.js'],
  ['Verification source tables', 'scripts/audit_verification_sources.js'],
  ['Outreach register', 'scripts/audit_outreach_register.js'],
  ['Outreach source index', 'scripts/test_outreach_source_index.js'],
  ['Site health', 'scripts/audit_site_health.js'],
  ['Homepage content', 'scripts/audit_homepage_content.js'],
  ['Update center content', 'scripts/audit_update_center_content.js'],
  ['Search content', 'scripts/audit_search_content.js'],
  ['News page content', 'scripts/audit_news_page_content.js'],
  ['News detail pages content', 'scripts/audit_news_detail_pages_content.js'],
  ['Page index', 'scripts/audit_page_index.js'],
  ['Sitemap', 'scripts/audit_sitemap.js'],
  ['News data', 'scripts/audit_news_data.js'],
  ['RSS', 'scripts/audit_rss.js'],
  ['Run checks helper', 'scripts/test_run_checks.js']
];

runChecks(checks, {
  successMessage: 'Project mode audits OK'
});