const assert = require('assert');
const fs = require('fs');
const path = require('path');
const core = require('../assets/js/home-discovery-core.js');
const ROOT = process.cwd();
const toses = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'toses.json'), 'utf8'));
const events = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'events.json'), 'utf8'));
const news = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'news.json'), 'utf8'));
const health = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'site_health.json'), 'utf8'));
assert.strictEqual(core.normalize('Подстёпки'), 'подстепки');
assert.strictEqual(core.searchToses(toses, 'п').length, 0);
assert(core.searchToses(toses, 'Подстепки').some((item) => item.slug === 'podstepki'));
assert(core.searchToses(toses, 'Чигорак').length >= 4);
assert.strictEqual(core.searchToses([{ name: 'Черновик', status: 'draft', slug: 'draft' }], 'черновик').length, 0);
const overview = core.buildCurrentOverview({ events, news, health, now: new Date('2026-07-17T12:00:00+03:00'), freshDays: 30 });
assert(overview.upcoming.length > 0);
assert.strictEqual(overview.upcoming[0].date, '2026-08-01');
assert.strictEqual(overview.freshNews.length, 1);
assert(overview.latestNews && overview.latestNews.date === '2026-06-24');
assert.strictEqual(overview.catalog.total_tos, 24);
console.log(`Home discovery OK: ${toses.length} cards, ${overview.upcoming.length} upcoming items, ${overview.freshNews.length} fresh news`);
