const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {
  findStaleGeneratedDirectories,
  removeStaleGeneratedDirectories
} = require('./lib/generated_page_cleanup');

const marker = 'AUTOGENERATED DETAIL PAGE';
const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'tos-generated-pages-'));

function writePage(id, body) {
  const directory = path.join(tempRoot, id);
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'index.html'), body, 'utf8');
}

try {
  writePage('current-page', marker);
  writePage('stale-page', marker);
  writePage('manual-page', 'Manual page without generated marker');
  fs.mkdirSync(path.join(tempRoot, 'empty-directory'));
  fs.writeFileSync(path.join(tempRoot, 'index.html'), 'Collection index', 'utf8');

  const stale = findStaleGeneratedDirectories({
    rootDir: tempRoot,
    validIds: ['current-page', 'current-page'],
    marker
  });

  assert.deepStrictEqual(stale.map((entry) => entry.id), ['stale-page']);

  const removed = removeStaleGeneratedDirectories({
    rootDir: tempRoot,
    validIds: ['current-page'],
    marker
  });

  assert.deepStrictEqual(removed, ['stale-page']);
  assert.strictEqual(fs.existsSync(path.join(tempRoot, 'stale-page')), false);
  assert.strictEqual(fs.existsSync(path.join(tempRoot, 'current-page', 'index.html')), true);
  assert.strictEqual(fs.existsSync(path.join(tempRoot, 'manual-page', 'index.html')), true);
  assert.strictEqual(fs.existsSync(path.join(tempRoot, 'empty-directory')), true);
  assert.deepStrictEqual(
    findStaleGeneratedDirectories({ rootDir: path.join(tempRoot, 'missing'), validIds: [], marker }),
    []
  );
  assert.deepStrictEqual(
    findStaleGeneratedDirectories({ rootDir: tempRoot, validIds: [], marker: '' }),
    []
  );

  console.log('Generated page cleanup helper OK: stale generated removed, current and manual pages preserved');
} finally {
  fs.rmSync(tempRoot, { recursive: true, force: true });
}
